# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name: "all"
  scenarios:
    enable: true
    file: config/scenarios_porto.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - 2
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  #- 2020
  - 2030
  - 2040
  #- 2050

countries: ['IT']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true
  custom_busmap: false
  drop_leap_day: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2-budget
co2_budget:
  2020: 10 # average emissions of 2019 to 2021 relative to 1990, CO2 excl LULUCF, EEA data, European Environment Agency. (2023a). Annual European Union greenhouse gas inventory 1990–2021 and inventory report 2023 - CRF Table. https://unfccc.int/documents/627830
  2025: 10 # With additional measures (WAM) projection, CO2 excl LULUCF, European Environment Agency. (2023e). Member States’ greenhouse gas (GHG) emission projections 2023. https://www.eea.europa.eu/en/datahub/datahubitem-view/4b8d94a4-aed7-4e67-a54c-0623a50f48e8
  2030: 10
  2035: 10
  2040: 10
  2045: 10
  2050: 10

weather_years:
  enable: true
  rcp: 2-6
# RCP 2.6 is 2-6, RCP 4.5 is 4-5, RCP 8.5 is 8-5
  global_regional_models: CNRM-CERFACS-CM5--CNRM-ALADIN63
# Global Climate Models (GCMs): CNRM-CERFACS-CM5, MPI-M-MPI-ESM-LR, MIROC-MIROC5
# Regional Climate Models (RCMs): CNRM-ALADIN63, ICTP-RegCM4-6, CLMcom-CLM-CCLM4-8-17
# Global model 1 has to be connected to regional model 1, so e.g. CNRM_CERFACS_CM5__CNRM_ALADIN63 but not CNRM_CERFACS_ICTP-RegCM4-6
  

remove_import: true
javier: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc, OCGT, CCGT]
    StorageUnit: [] # battery, H2
    Store: [battery]
    Link: [] # H2 pipeline
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
  max_hours:
    battery: 3

# docs
# TODO: PyPSA-Eur merge issue in prepare_sector_network.py
# regulate what components with which carriers are kept from PyPSA-Eur;
# some technologies are removed because they are implemented differently
# (e.g. battery or H2 storage) or have different year-dependent costs
# in PyPSA-Eur-Sec
pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - solar
  - ror
  - nuclear
  StorageUnit:
  - PHS
  - hydro
  Store: []

existing_capacities:
  default_heating_lifetime: 40
  grouping_years_power: [2020]

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  agriculture: true
  fossil_fuels: true
  bev_dsm: false
  v2g: false
  co2_sequestration_potential:
    2020: 0
    2025: 0
    2030: 50
    2035: 100
    2040: 200
    2045: 200
    2050: 200
  min_part_load_fischer_tropsch: 0.5
  H2_network: false
  apply_ctax:
    enable: false
    file: "data/200225 Carbon Tax Alice.xlsx"
  tes: false
  # This wildcard is not working if only in config.default.yaml (I have no idea why)
  chp:
    enable: true
    fuel:
    - solid biomass # For solid biomass, CHP with and without CC are added
    micro_chp: false # Only gas is used for micro_chp
  electricity_distribution_grid: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  temporal:
    resolution_elec: false
    resolution_sector: false

transmission_projects:
  enable: false

solving:
  solver_options:
    gurobi-default:
      BarHomogeneous: 1