# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#

# s1: low carbon price
# s2: high carbon price
s1:
  sector:
    apply_ctax:
      enable: true
      file: "data/ctax_s1.xlsx"

  costs:
    fill_values:
      "discount rate": 0.04

s1_noctax:
  sector:
    apply_ctax:
      enable: false

  costs:
    fill_values:
      "discount rate": 0.04


s2:
  sector:
    apply_ctax:
      enable: true
      file: "data/ctax_s2.xlsx"

  costs:
    fill_values:
      "discount rate": 0.02

  
# NEW ONES
low_ctax:
  sector:
    apply_ctax:
      enable: true
      file: "data/ctax_s1.xlsx"

  javier: false

high_ctax:
  sector:
    apply_ctax:
      enable: true
      file: "data/ctax_s2.xlsx"

  javier: false

low_discount:
  sector:
    apply_ctax:
      enable: false

  javier: true
  costs:
    fill_values:
      "discount rate": 0.02

high_discount:
  sector:
    apply_ctax:
      enable: false

  javier: true
  costs:
    fill_values:
      "discount rate": 0.04