# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

hist:
  scenario:
    planning_horizons:
    - 2020
  energy:
    base_emissions_year: 2018


baseline:
  sector:
    fidelio:
      scenario: baseline

ff55:
  sector:
    fidelio:
      scenario: ff55